# Generated by Django 4.1.4 on 2022-12-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0002_alter_photo_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="file",
            field=models.URLField(),
        ),
    ]
